import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased bg-white-bg dark:bg-black-bg text-black-fg dark:text-white-fg`}
      >
        <div className="font-[family-name:var(--font-geist-sans)] relative overflow-x-hidden">
          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
